config/routes.rb
Rails.application.routes.draw do

  root 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  #root 'subjects/index'
  #match "/", :to => "subjects#index", :via =>"get"

  get 'admin', :to => "access#menu"
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end
  
  resources :subjects do
    member do
      get :delete
    end
    resources :pages do
      member do
        get :delete
      end
      resources :sections do
        member do
          get :delete
        end
      end
    end
  end
  
end

app/views/pages/_form.html.erb
<%= error_message_for(f.object) %>

<table summary="Page form fields">
	<tr>
		<th>Name</th>
		<td><%= f.text_field(:name) %></td>
	</tr>
	<tr>
		<th>Subject</th>
		<td><%= @subject.name %></td>
	</tr> 
	<tr>
		<th>Permalink</th>
		<td><%= f.text_field(:permalink) %></td>
	</tr>
	<tr>
		<th>Position</th>
		<td><%= f.select(:position,1..@pages_count) %></td>
	</tr>
	<tr>
		<th>Visible?</th>
		<td><%= f.check_box(:visible) %></td>
	</tr>
</table>

app/views/pages/delete.html.erb
<% @page_title = "Delete "+@page.name+" Page" %>
<%= link_to("<< Back to List", subject_pages_path(@subject), :class => 'back-link') %>
<div>
	<h2>Delete Page</h2>
	<%= form_for(@page, :url => subject_page_path(@page, @subject), :method => 'delete') do |f| %>
	 	<p>Are you sure you want to delete this page?</p>
	 	<%= @page.name %>

	 	<div>
	 		<%= f.submit("Delete Subject") %>
	 	</div>

	<%end%>
</div>

app/views/pages/edit.html.erb
<% @page_title = "Edit "+@page.name+" Page" %>
<%= link_to("<< Back to Pages List", subject_pages_path(@subject), :class => 'back-link') %>

<div class="pages edit">
	<%= form_for(@page, :url => subject_page_path(@page, @subject)) do |f| %>
		
		<%= render(:partial => 'form', :locals =>{:f => f}) %>

	<div class="form-buttons">
      <%= f.submit("Update Page") %>
    </div>
	<% end %>
</div>

app/views/pages/index.html.erb
<% @page_title = "Pages" %>
<div class="pages index">
	<h2>Pages for: <%=@subject.name%></h2>
	<%= link_to("Add new Page", new_subject_page_path(@subject),:class => 'action new') %>

	<table class="listing" summary="Page list">
		<tr class="header">
			<th>#</th>
			<th>Subject ID</th>
			<th>Name</th>
			<th>Permalink</th>
			<th>Visible</th>
			<th>Sections</th>
			<th>Actions</th>
		</tr>
		<% @pages.each do |page| %>
		<tr>
			<td><%= page.position %></td>
			<td><%= page.subject_id %></td>
			<td><%= page.name %></td>
			<td><%= page.permalink %></td>
			<td class="center"><%= status_tag(page.visible)%>
			<td class="center"><%= page.sections.size %></td>
			</td>
			<td class="actions">
				<%= link_to("View Sections", subject_page_sections_path(@subject, page), :class => 'action show') %>
				<%= link_to("Show", subject_page_path(page, @subject), :class => 'action show') %>
				<%= link_to("Edit", edit_subject_page_path(page, @subject), :class => 'action edit') %>
				<%= link_to("Delete", delete_subject_page_path(page, @subject), :class => 'action delete') %>
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/pages/new.html.erb
<% @page_title = "New Page" %>
<%= link_to("<< Back to List", subject_pages_path(@subject), :class => 'back-link') %>
<div class="pages new">
	<h2>Create Page</h2>
	<%= form_for(@page, :url => subject_pages_path(@subject)) do |f| %>
		<%= render(:partial=>'form', :locals=>{:f=>f})%>
		<div class="form-buttons">
	      <%= f.submit("Create Page") %>
	    </div>
	    <% Rails.logger.debug params.inspect %>
	<% end %>
</div>

app/views/pages/show.html.erb
<% @page_title = "Page "+@page.name %>
<div>
	<%= link_to("<<Back to pages", subject_pages_path(@subject), :class => 'back-link') %>
	<h2>Show Page '<%=@page.name %>'</h2>

	<div class="pages show">
		<h2>Show Page</h2>

		<table summary="Page detail view">
		<tr>
			<th>Name</th>
			<td><%= @page.name %></td>
		</tr>
		<tr>
			<th>Subject ID</th>
			<td><%= @page.subject_id %></td>
		</tr>
		<tr>
			<th>Permalink</th>
			<td><%= @page.permalink %></td>
		</tr>
		<tr>
			<th>Position</th>
			<td><%= @page.position %></td>
		</tr>
		<tr>
			<th>Visible</th>
			<td><%= @page.visible ? 'Yes' : 'No' %></td>
		</tr>
		<tr>
			<th>Created</th>
			<td><%= @page.created_at %></td>
		</tr>
		<tr>
			<th>Updated</th>
			<td><%= @page.updated_at %></td>
		</tr>
	</table>
	</div>
</div>