config/routes.rb
Rails.application.routes.draw do

  root 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  #root 'subjects/index'
  #match "/", :to => "subjects#index", :via =>"get"

  get 'admin', :to => "access#menu"
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end
  
  resources :subjects do
    member do
      get :delete
    end
    resources :pages do
      member do
        get :delete
      end
      resources :sections do
        member do
          get :delete
        end
      end
    end
  end
  
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

	has_secure_password

	has_and_belongs_to_many :pages
	has_many :section_edits
	has_many :sections, :through => :section_edits

	scope :sorted, lambda{ order('last_name ASC', 'first_name ASC') }

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

	validates :first_name, :presence => true,
			  :length => { :maximum => 25 }
	validates :last_name, :presence => true,
	          :length => { :maximum => 50 }
	validates :username, :length => { :within => 4..25 },
	          :uniqueness => true
	validates :email, :presence => true,
              :length => { :maximum => 100 },
              :format => EMAIL_REGEX,
              :confirmation => true,
              :uniqueness => true
    def name
    	"#{first_name} #{last_name}"
    end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  
  layout 'admin'

  before_action :confirm_logged_in

  def index
    @admin_users = AdminUser.sorted
  end

  def new
    @admin_user = AdminUser.new
  end

  def create
    @admin_user = AdminUser.new(admin_user_params)
    if @admin_user.save
      flash[:notice] = "Admin User Created Successfully!"
      redirect_to(admin_users_path)
    else
      render ('new')
    end
  end

  def edit
    @admin_user = AdminUser.find(params[:id])
  end

  def update
    @admin_user = AdminUser.find(params[:id])
    if @admin_user.update_attributes(admin_user_params)
      flash[:notice] = "Admin User Updated Successfully!"
      redirect_to(admin_users_path)
    else
      render('new')
    end
  end

  def delete
    @admin_user = AdminUser.find(params[:id])
  end

  def destroy
    @admin_user = AdminUser.find(params[:id])
    @admin_user.destroy
    flash[:notice] = "Admin User #{@admin_user.name} deleted Successfully!"
    redirect_to(admin_users_path)
  end

  private
  def admin_user_params
    params.require(:admin_user).permit(:first_name,:last_name,:email,:password,:username)
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<%= error_message_for(f.object) %>

<table>
	<tr>
		<th><%= f.label(:first_name) %></th>
		<td><%= f.text_field(:first_name) %></td>
	</tr>
	<tr>
		<th><%= f.label(:last_name) %></th>
		<td><%=f.text_field(:last_name)%></td>
	</tr>
	<tr>
		<th><%= f.label(:email) %></th>
		<td><%= f.email_field(:email) %></td>
	</tr>
	<tr>
		<th><%= f.label(:username) %></th>
		<td><%= f.text_field(:username) %></td>
	</tr>
	<tr>
		<th><%= f.label(:password) %></th>
		<td><%= f.password_field(:password) %></td>
	</tr>
</table>

app/views/admin_users/create.html.erb
<h1>AdminUsersController#create</h1>
<p>Find me in app/views/admin_users_controller/create.html.erb</p>

app/views/admin_users/delete.html.erb
<% @page_title = "Delete Admin User" %>

<%= link_to("<< Back to List", admin_users_path, :class => "back-line") %>
<div class="admin-users delete">
	<h2>Delete Admin User</h2>

	<%= form_for(@admin_user, :url => admin_user_path(@admin_user), :method => 'delete') do |f| %>
		<p>Are you sure you want to permanently delete this admin user?</p>
		<p class="reference-name"><%= f.object.name %></p>

		<div class="form-buttons">
			<%= f.submit("Delete Admin User") %>
		</div>
	<% end %>
</div>

app/views/admin_users/destroy.html.erb
<h1>AdminUsersController#destroy</h1>
<p>Find me in app/views/admin_users_controller/destroy.html.erb</p>

app/views/admin_users/edit.html.erb
<% @page_title = "Update "+@admin_user.first_name+" Page" %>
<%= link_to("Back to Admin Users List", admin_users_path) %>
<h2>Update Admin User: <%=@admin_user.first_name%></h2>
<div>
	<%= form_for(@admin_user, :url => admin_user_path(@admin_user)) do |f| %>
		<%= render(:partial => 'form', :locals => {:f => f}) %>
		<div class="form-buttons">
	      <%= f.submit("Update") %>
	    </div>
	<% end %>
</div>

app/views/admin_users/index.html.erb
<% @page_title = "All Admin Users" %>

<%= link_to("Back to menu", admin_path) %>

<div class="admin-users index">
	
	<h2>Admin Users</h2>

	<%= link_to("Add new Admin User", new_admin_user_path, :class => 'action new') %>

	<div><%= pluralize(@admin_users.size, 'admin user') %> found.</div>

	<table class="listing" summary="admin list">
		<tr class="header">
			<th>Username</th>
			<th>Name</th>
			<th>Email</th>
			<th>Actions</th>
		</tr>
		<% @admin_users.each do |admin_user| %>
		<tr>
			<td> <%= admin_user.username %> </td>
			<td> <%= admin_user.name %> </td>
			<td> <%= mail_to(admin_user.email) %> </td>
			<td class="actions"> 
				<%= link_to("Edit", edit_admin_user_path(admin_user), :class => 'action edit') %>

				<%= link_to("Delete",delete_admin_user_path(admin_user), :class => 'action delete') %>
			</td>
		</tr>
		<% end %>
	</table>
</div>

app/views/admin_users/new.html.erb
<% @page_title = "Add new Admin User" %>
<%= link_to("Back to Admin Users List", admin_users_path) %>
<h2>Add new admin user</h2>
<div>
	<%= form_for(@admin_user, :url => admin_users_path) do |f|%> 
		
	<%= render(:partial => 'form', :locals => {:f => f})%>
	<div class="form-buttons">
      <%= f.submit("Create Admin User") %>
    </div>
	<% end %>
</div>

app/views/admin_users/update.html.erb
<h1>AdminUsersController#update</h1>
<p>Find me in app/views/admin_users_controller/update.html.erb</p>